name: Build docs

on:
  push:
  release:
    types:
      - published
  workflow_dispatch:

# Gives the workflow permissions to clone the repo and create a page deployment
permissions:
  id-token: write
  pages: write

# Allow one concurrent deployment
concurrency:
      group: pages
      cancel-in-progress: true

# This workflow updates the versioned docs on dokka.kord.dev using the following strategy
# 1) pull cache to docs-cache
# 2) Call dokkaHtmlMultiModule for current version
#   - if this is a release build move current docs into docs-cache/$version
#   - otherwise move it into docs-cache/current
# 3) Build GitHub Pages artifact
#   - Move all folders not named "current" into docs/<folder>
#   - Move current into docs/
# 4) Trigger a deployment to GitHub Actions
jobs:
  build-job:
    if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    env:
      GITHUB_TAG_NAME: ${{ github.event.release.tag_name }}
      GITHUB_BRANCH_NAME: ${{ github.ref }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Checkout cache
        with:
          ref: 'docs-cache'
          path: 'docs-cache'
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 8
      - name: Build docs with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: :produceDocs
      - name: Commit files
        working-directory: docs-cache
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -a -m "Add changes"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: docs-cache
          directory: docs-cache
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: docs
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
