name: GraalVM Native Image CI

on:
  push:
  pull_request:

jobs:
  test-on-graalvm-native-image:
    name: Test Kord on GraalVM Native Image
    runs-on: ${{ matrix.os }}
    env:
      KORD_TEST_TOKEN: ${{ secrets.KORD_TEST_TOKEN }}
    strategy:
      matrix:
        os: [ macos-latest ]
    steps:
      - uses: actions/checkout@v3
      - uses: graalvm/setup-graalvm@v1
        with:
          version: latest
          java-version: 17
          components: native-image
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Add msbuild to PATH
        if: ${{ matrix.os == 'windows-latest' }}
        uses: microsoft/setup-msbuild@v1
      - name: Test with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: --stacktrace --info nativeTest
