name: GraalVM Native Image CI

on:
  push:
  pull_request:

jobs:
  build:
    name: Build Kord
    runs-on: ubuntu-latest
    env:
      KORD_TEST_TOKEN: ${{ secrets.KORD_TEST_TOKEN }}
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: graalvm/setup-graalvm@v1
        with:
          version: 'latest'
          java-version: '17'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: nativeTest
